name: Publish to GitHub Packages

on:
  push:
    branches:
      - feature/
      - release-*

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: sbt

      - name: Publish
        run: sbt clean +publish
        env:
          USER: ${{ secrets.USER }}
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
