name: Prepare release
run-name: Prepare release ${{ github.event.inputs.release }}

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true
        type: string
permissions:
  contents: write
  pull-requests: write
  
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Update version.sbt
        run: |
          echo "version := \"${{ github.event.inputs.release }}\"" > version.sbt
          echo "cat version.sbt"
          cat version.sbt


      - name: Create release branch and commit changes
        run: |
          git checkout -b release/${{ github.event.inputs.release }}
          git add version.sbt
          git commit -m "Update version to ${{ github.event.inputs.release }}"
          git push origin release/${{ github.event.inputs.release }}
